### PR TITLE
Fixed broken lock screen play button

### PR DESCRIPTION
**Pull request by Ingvix**
Btw, do you have a vector file or a whole version of vlc_cover.png? The current one does not look nice with devices with a screen larger than jolla1's and I could make it a bit more fitting. I can do it without it but it would be easier especially if you got a vector file of it.

### CODE REVIEW

**Comment by Mariusmssj** [comment]
Thanks for the fix :) Also sorry I do not have the vector images BUT they were made by a SailfishOS user https://twitter.com/capricotwi I will try to get in touch with him to check if he still might have it.

**Comment by Ingvix** [comment]
Any news about the icons?

**Comment by Mariusmssj** [comment]
Hi Ingvix,


I contacted Caprico and he did say he will redo them, but from that I gather he is currently on a holiday. Once I know more I will let you know [😊]

Regards,

Marius


________________________________

**Comment by Mariusmssj** [comment]
Hi Ingvix,

Got a response from Caprico and he'll get the icon sorted by the end of the week. Once he does I will forward them to you.

Regards,
Marius

**Comment by Ingvix** [comment]
Well, I don't think there's not much for me to do if he fixes the icon. The best solution would be to use the svg file in the cover so the image could be scaled without loss in quality.

**Comment by Mariusmssj** [comment]
There we go.
[vlc_cover.zip](https://github.com/Mariusmssj/harbour-vlc-remote/files/1011887/vlc_cover.zip)

**Pull request merged**
